# Generated by Django 5.2 on 2025-05-24 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homelight_users', '0011_alter_customers_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_type',
            fields=[
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'issue_type',
            },
        ),
        migrations.CreateModel(
            name='customer_requests',
            fields=[
                ('updated_at', models.TimeField(auto_created=True)),
                ('created_at', models.TimeField(auto_created=True)),
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.CharField(max_length=100)),
                ('video_file_path', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('EVCPLUS', 'EVCPLUS'), ('MARCHENT', 'MARCHENT'), ('CREDITCARD', 'CREDITCARD')], default='EVCPLUS', max_length=20)),
                ('ar_support_enabled', models.BooleanField(default=False)),
                ('requested_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed'), ('In Progress', 'In Progress')], default='Pending', max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_users.customers')),
                ('technician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_users.technicians')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.issue_type')),
            ],
            options={
                'db_table': 'customer_requests',
            },
        ),
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('due_date', models.TimeField(auto_created=True)),
                ('invoice_date', models.TimeField(auto_created=True)),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], default='UNPAID', max_length=20)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.customer_requests')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='payment_transactions',
            fields=[
                ('transaction_date', models.TimeField(auto_created=True)),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_method', models.CharField(choices=[('EVCPLUS', 'EVCPLUS'), ('MARCHENT', 'MARCHENT'), ('CREDITCARD', 'CREDITCARD')], default='EVCPLUS', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.customer_requests')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='technician_service_pricing_history',
            fields=[
                ('changed_at', models.TimeField(auto_created=True)),
                ('pricing_his_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.issue_type')),
                ('technician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_users.technicians')),
            ],
            options={
                'db_table': 'technician_service_pricing_history',
            },
        ),
        migrations.CreateModel(
            name='technician_services',
            fields=[
                ('created_at', models.TimeField(auto_created=True)),
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.issue_type')),
                ('technician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_users.technicians')),
            ],
            options={
                'db_table': 'technician_services',
            },
        ),
        migrations.CreateModel(
            name='customer_service_bookmarks',
            fields=[
                ('updated_at', models.TimeField(auto_created=True)),
                ('created_at', models.TimeField(auto_created=True)),
                ('bookmark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='UNPAID', max_length=20)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.technician_services')),
            ],
            options={
                'db_table': 'customer_service_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='troubleshooting_history',
            fields=[
                ('resolved_at', models.TimeField(auto_created=True)),
                ('trouble_shoot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_text', models.CharField(max_length=30)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.customer_requests')),
            ],
            options={
                'db_table': 'troubleshooting_history',
            },
        ),
    ]
