# Generated by Django 5.2 on 2025-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_type',
            name='issue_icon',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
