# Generated by Django 5.2 on 2025-06-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0002_issue_type_issue_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_requests',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='customer_requests',
            name='technician_id',
        ),
    ]
