# Generated by Django 5.2 on 2025-06-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0003_remove_customer_requests_issue_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_requests',
            name='issue_description',
        ),
        migrations.AddField(
            model_name='customer_requests',
            name='issue_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.issue_type'),
            preserve_default=False,
        ),
    ]
