# Generated by Django 5.2 on 2025-06-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0004_remove_customer_requests_issue_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_requests',
            name='video_file_path',
        ),
    ]
