# Generated by Django 5.2 on 2025-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0005_remove_customer_requests_video_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_requests',
            name='audio_description',
            field=models.FileField(blank=True, null=True, upload_to='audio_descriptions/'),
        ),
        migrations.AddField(
            model_name='customer_requests',
            name='issue_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_requests',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
