# Generated by Django 5.2 on 2025-06-14 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0006_customer_requests_audio_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

