# Generated by Django 5.2 on 2025-06-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0009_customer_requests_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_requests',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer_requests',
            name='updated_at',
        ),
    ]
