# Generated by Django 5.2 on 2025-06-15 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0010_remove_customer_requests_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_gallery',
            fields=[
                ('gallery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gallery_url', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='audio_descriptions/')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.customer_requests')),
            ],
            options={
                'db_table': 'request_gallery',
            },
        ),
    ]
