# Generated by Django 5.2 on 2025-06-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0011_request_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_requests',
            name='audio_description',
        ),
    ]
