# Generated by Django 5.2 on 2025-06-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0012_remove_customer_requests_audio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_services',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='technician_services',
            name='issue_id',
        ),
        migrations.AddField(
            model_name='technician_service_pricing_history',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='technician_services',
            name='request_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.customer_requests'),
            preserve_default=False,
        ),
    ]
