# Generated by Django 5.2 on 2025-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0013_remove_technician_services_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician_services',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
