# Generated by Django 5.2 on 2025-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0014_alter_technician_services_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_services',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='audio_services/'),
        ),
    ]
