# Generated by Django 5.2 on 2025-06-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0015_technician_services_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_services',
            name='technician_id',
        ),
    ]
