# Generated by Django 5.2 on 2025-06-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0017_technician_services_technician_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_history',
            name='resolved_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
