# Generated by Django 5.2 on 2025-06-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0018_alter_troubleshooting_history_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_history',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.technician_services'),
        ),
    ]
