# Generated by Django 5.2 on 2025-06-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0019_alter_troubleshooting_history_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_services',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='troubleshooting_history',
            name='resolved_at',
        ),
    ]
