# Generated by Django 5.2 on 2025-06-24 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0020_remove_technician_services_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troubleshooting_history',
            name='resolved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
