# Generated by Django 5.2 on 2025-06-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0021_technician_services_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician_services',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_services_set', to='homelight_appointment.customer_requests'),
        ),
        migrations.AlterField(
            model_name='troubleshooting_history',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshooting_history_set', to='homelight_appointment.technician_services'),
        ),
    ]
