# Generated by Django 5.2 on 2025-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0022_alter_technician_services_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_history',
            name='resolution_text',
            field=models.TextField(),
        ),
    ]
