# Generated by Django 5.2 on 2025-06-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0023_alter_troubleshooting_history_resolution_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_services',
            name='estimated_duration',
        ),
    ]
