# Generated by Django 5.2 on 2025-06-30 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0024_remove_technician_services_estimated_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_services',
            name='custom_price',
        ),
        migrations.AddField(
            model_name='technician_services',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
