# Generated by Django 5.2 on 2025-06-30 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0025_remove_technician_services_custom_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician_services',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
