# Generated by Django 5.2 on 2025-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0026_alter_technician_services_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_services',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
