# Generated by Django 5.2 on 2025-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0027_technician_services_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_requests',
            name='issue_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='technician_services',
            name='notes',
            field=models.CharField(max_length=500),
        ),
    ]
