# Generated by Django 5.2 on 2025-07-15 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0028_alter_customer_requests_issue_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='troubleshooting_gallery',
            fields=[
                ('gallery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gallery_url', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='audio_descriptions/')),
                ('trouble_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.troubleshooting_history')),
            ],
            options={
                'db_table': 'troubleshooting_gallery',
            },
        ),
    ]
