# Generated by Django 5.2 on 2025-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0029_troubleshooting_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_gallery',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='trouble_audio/'),
        ),
        migrations.AlterField(
            model_name='troubleshooting_gallery',
            name='gallery_url',
            field=models.FileField(blank=True, null=True, upload_to='trouble_gallery/'),
        ),
    ]
