# Generated by Django 5.2 on 2025-07-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0030_alter_troubleshooting_gallery_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshooting_gallery',
            name='trouble_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='homelight_appointment.troubleshooting_history'),
        ),
    ]
