# Generated by Django 5.2 on 2025-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0031_alter_troubleshooting_gallery_trouble_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_services',
            name='status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Accept', 'Accept')], default='Reject', max_length=20),
        ),
    ]
