# Generated by Django 5.2 on 2025-07-21 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0032_technician_services_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='payment_transactions',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='payment_transactions',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment_transactions',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='payment_transactions',
            name='invoice_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.invoices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE'), ('REFUNDED', 'REFUNDED')], default='OVERDUE', max_length=20),
        ),
    ]
