# Generated by Django 5.2 on 2025-07-21 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0033_remove_invoices_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
