# Generated by Django 5.2 on 2025-07-21 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0034_invoices_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_transactions',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
