# Generated by Django 5.2 on 2025-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0036_alter_technician_services_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician_services',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Select', 'Select')], default='Select', max_length=20),
        ),
    ]
