# Generated by Django 5.2 on 2025-07-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0037_alter_technician_services_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.technician_services'),
        ),
    ]
