# Generated by Django 5.2 on 2025-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0041_invoices_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_services',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
