# Generated by Django 5.2 on 2025-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0042_technician_services_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician_services',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
