# Generated by Django 5.2 on 2025-07-23 12:06

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0043_alter_technician_services_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='technician_service_history',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('notes', models.CharField(max_length=500)),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='audio_services/')),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Select', 'Select')], default='Select', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.customer_requests')),
                ('technician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technician_service_history',
            },
        ),
        migrations.DeleteModel(
            name='technician_service_pricing_history',
        ),
    ]
