# Generated by Django 5.2 on 2025-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0044_technician_service_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_service_history',
            name='service_id',
        ),
        migrations.AddField(
            model_name='technician_service_history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
