# Generated by Django 5.2 on 2025-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0045_remove_technician_service_history_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician_service_history',
            name='service_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
