# Generated by Django 5.2 on 2025-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0046_technician_service_history_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_transactions',
            name='number_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
