# Generated by Django 5.2 on 2025-07-26 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0047_payment_transactions_number_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE'), ('REFUNDED', 'REFUNDED'), ('WAITINGVARIFICATION', 'WAITINGVARIFICATION')], default='OVERDUE', max_length=20),
        ),
        migrations.CreateModel(
            name='calenders',
            fields=[
                ('calender_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calenders',
            },
        ),
    ]
