# Generated by Django 5.2 on 2025-07-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0048_alter_invoices_status_calenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenders',
            name='activity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
