# Generated by Django 5.2 on 2025-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0049_calenders_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE'), ('REFUND', 'REFUND'), ('WAITINGVARIFICATION', 'WAITINGVARIFICATION')], default='OVERDUE', max_length=20),
        ),
    ]
