# Generated by Django 5.2 on 2025-07-28 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0050_alter_invoices_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE'), ('REFUND', 'REFUND'), ('WAITINGVARIFICATION', 'WAITINGVARIFICATION')], default='OVERDUE', max_length=20)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homelight_appointment.technician_services')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_history',
            },
        ),
    ]
