# Generated by Django 5.2 on 2025-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0051_invoice_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_history',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE'), ('REFUND', 'REFUND'), ('REFUNDED', 'REFUNDED'), ('WAITINGVARIFICATION', 'WAITINGVARIFICATION')], default='OVERDUE', max_length=20),
        ),
    ]
