# Generated by Django 5.2 on 2025-05-20 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0002_alter_customers_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technicians',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
