# Generated by Django 5.2 on 2025-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0003_technicians_registered_at_and_more'),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name='technicians',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
