# Generated by Django 5.2 on 2025-05-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0004_remove_technicians_registered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='registered_at',
        ),
    ]
