# Generated by Django 5.2 on 2025-05-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0005_remove_technicians_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='technicians',
            name='updated_at',
        ),
    ]
