# Generated by Django 5.2 on 2025-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0007_technicians_created_at_technicians_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
