# Generated by Django 5.2 on 2025-05-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0008_alter_customers_total_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='updated_at',
        ),
    ]
