# Generated by Django 5.2 on 2025-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0010_customers_created_at_customers_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
