# Generated by Django 5.2 on 2025-08-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0011_alter_customers_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='total_bookings',
        ),
        migrations.RemoveField(
            model_name='technicians',
            name='main_specialty',
        ),
        migrations.RemoveField(
            model_name='technicians',
            name='years_of_experience',
        ),
    ]
