# Generated by Django 5.2 on 2025-08-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0012_remove_customers_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='review_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
