# Generated by Django 5.2 on 2025-08-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0013_technicians_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='review_rate',
        ),
    ]
