# Generated by Django 5.2 on 2025-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0015_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
