# Generated by Django 5.2 on 2025-08-09 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_users', '0017_alter_reviews_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviewed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_made', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
