# Generated by Django 5.2 on 2025-07-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_appointment', '0028_alter_customer_requests_issue_description_and_more'),
        ('homelight_technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_gallery',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='homelight_appointment.issue_type'),
        ),
    ]
