# Generated by Django 5.2 on 2025-07-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelight_technician', '0003_technician_specialization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician_specialization',
            name='technician_id',
        ),
    ]
